### ISSUE TITLE
Schema name is limited to 63 characters, but the test is for less than 63

### ISSUE THREAD

**Issue by moltar** [faxm0dem/Test-Collectd-Plugins#4]
I think it should be less or equal, rather than just less.

https://collectd.org/wiki/index.php/Naming_schema

https://github.com/faxm0dem/Test-Collectd-Plugins/blob/master/lib/Test/Collectd/Plugins.pm#L255

**Comment by faxm0dem** [comment]
I gave this some thought, and I think this test is still useful (when using the `collectd-network` plugin).
However, I agree it may not be relevant for other use-cases.
Therefore, what do you think about a configuration option to disable that subtest for `read_ok` and `load_ok`?

**Comment by moltar** [comment]
Yeah, config option would be great.
